# from runtime import eprint, say, reply, replypos, replyend, createtextchannel, createvoicechannel, requestauthor, requestnotauthor, requestrole, requestnotrole, requestchannel, requestnotchannel, requestbot, embed, requestchanneltype, clear, replykick, kick, replyban, ban, opendm, requestmessage, requestnotmessage, setstatus, setactivity, sleep

# methods = {
# 	    "print": eprint,
#       "say": say,
# 	    "reply": reply,
# 	    "replypos": replypos,
# 	    "replyend": replyend,
# 	    "createtextchannel": createtextchannel,
# 	    "createvoicechannel": createvoicechannel,
#       "requestauthor": requestauthor,
#       "requestnotauthor": requestnotauthor,
#       "requestrole": requestrole,
#       "requestnotrole": requestnotrole,
#       "requestchannel": requestchannel,
#       "requestnotchannel": requestnotchannel,
# 	    "requestbot": requestbot,
# 	    "embed": embed,
# 	    "requestchanneltype": requestchanneltype,
#       "clear": clear,
#       "replykick": replykick,
#       "kick": kick,
#       "replyban": replyban,
#       "ban": ban,
#       "opendm": opendm,
#       "igrequestauthor": requestauthor,
#       "igrequestnotauthor": requestnotauthor,
#       "igrequestrole": requestrole,
#       "igrequestnotrole": requestnotrole,
#       "igrequestchannel": requestchannel,
#       "igrequestnotchannel": requestnotchannel,
# 	    "igrequestbot": requestbot,
# 	    "igrequestchanneltype": requestchanneltype,
#       "requestmessage": requestmessage,
#       "requestnotmessage": requestnotmessage,
#       "igrequestmessage": requestmessage,
#       "igrequestnotmessage": requestnotmessage,
#       "setstatus": setstatus,
#       "setactivity": setactivity,
#       "sleep": sleep
#   }

# commands = methods.keys()
# commands = []
commands = [
  "setprefix",
  "print",
  "say",
  "reply",
  "replypos",
  "replyend",
  "createtextchannel",
  "createvoicechannel",
  "requestauthor",
  "requestnotauthor",
  "requestrole",
  "requestnotrole",
  "requestchannel",
  "requestnotchannel",
  "requestbot",
  "embed",
  "requestchanneltype",
  "clear",
  "replykick",
  "kick",
  "replyban",
  "ban",
  "opendm",
  "igrequestauthor",
  "igrequestnotauthor",
  "igrequestrole",
  "igrequestnotrole",
  "igrequestchannel",
  "igrequestnotchannel",
	"igrequestbot",
	"igrequestchanneltype",
  "requestmessage",
  "requestnotmessage",
  "igrequestmessage",
  "igrequestnotmessage",
  "setstatus",
  "setactivity",
  "sleep",
  "reaction",
  "reactionadd",
  "reactions",
  "reactionremove",
  "addreaction",
  "parsereactionpayload",
  "readjson",
  "writejson",
]